2025-04-11 09:25:19 - ½Å±¾Ö´ÐÐÊ§°Ü£¬·µ»ØÂë: 1
2025-04-11 09:25:19 - ´íÎóÊä³ö: Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\numpy\core\__init__.py", line 17, in <module>
    from . import multiarray
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\PyProject\QTneedle\QTneedle\Standard I-V test program use Keithley2450.py", line 14, in <module>
    from matplotlib import pyplot as plt
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\matplotlib\__init__.py", line 104, in <module>
    import numpy
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\numpy\core\__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.12 from "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.0" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'


2025-04-11 09:25:38 - ½Å±¾Ö´ÐÐÊ§°Ü£¬·µ»ØÂë: 1
2025-04-11 09:25:38 - ´íÎóÊä³ö: Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\numpy\core\__init__.py", line 17, in <module>
    from . import multiarray
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\PyProject\QTneedle\QTneedle\Standard I-V test program use Keithley2450.py", line 14, in <module>
    from matplotlib import pyplot as plt
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\matplotlib\__init__.py", line 104, in <module>
    import numpy
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\numpy\core\__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.12 from "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.0" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'


2025-04-11 09:28:11 - ½Å±¾Ö´ÐÐÊ§°Ü£¬·µ»ØÂë: 1
2025-04-11 09:28:11 - ´íÎóÊä³ö: Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\numpy\core\__init__.py", line 17, in <module>
    from . import multiarray
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\PyProject\QTneedle\QTneedle\Standard I-V test program use Keithley2450.py", line 14, in <module>
    from matplotlib import pyplot as plt
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\matplotlib\__init__.py", line 104, in <module>
    import numpy
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\numpy\core\__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.12 from "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.0" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'


2025-04-11 09:29:24 - ½Å±¾Ö´ÐÐÊ§°Ü£¬·µ»ØÂë: 1
2025-04-11 09:31:11 - ´íÎóÊä³ö: Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\numpy\core\__init__.py", line 17, in <module>
    from . import multiarray
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Pycharm\PyCharm 2024.3.3\plugins\python-ce\helpers\pydev\pydevd.py", line 1570, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Pycharm\PyCharm 2024.3.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:\PyProject\QTneedle\QTneedle\Standard I-V test program use Keithley2450.py", line 14, in <module>
    from matplotlib import pyplot as plt
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\matplotlib\__init__.py", line 104, in <module>
    import numpy
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\numpy\core\__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.12 from "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.0" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'


2025-04-11 09:33:25 - ½Å±¾Êä³ö: ---

2025-04-11 09:33:25 - ³É¹¦Ö´ÐÐIU²ÎÊý¼ÆËã
2025-04-11 09:33:45 - ½Å±¾Ö´ÐÐÊ§°Ü£¬·µ»ØÂë: 1
2025-04-11 09:33:45 - ´íÎóÊä³ö: Traceback (most recent call last):
  File "D:\PyProject\QTneedle\QTneedle\Standard I-V test program use Keithley2450.py", line 64, in <module>
    keithley.wires
  File "D:\PyProject\.venv\Lib\site-packages\pymeasure\instruments\common_base.py", line 298, in __getattribute__
    return super().__getattribute__(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyProject\.venv\Lib\site-packages\pymeasure\instruments\common_base.py", line 555, in fget
    vals = self.values(command_process(get_command),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyProject\.venv\Lib\site-packages\pymeasure\instruments\common_base.py", line 406, in values
    results = self.ask(command, **kwargs).strip()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyProject\.venv\Lib\site-packages\pymeasure\instruments\common_base.py", line 387, in ask
    return self.read()
           ^^^^^^^^^^^
  File "D:\PyProject\.venv\Lib\site-packages\pymeasure\instruments\instrument.py", line 173, in read
    return self.adapter.read(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyProject\.venv\Lib\site-packages\pymeasure\adapters\adapter.py", line 108, in read
    read = self._read(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\PyProject\.venv\Lib\site-packages\pymeasure\adapters\visa.py", line 172, in _read
    return self.connection.read(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyProject\.venv\Lib\site-packages\pyvisa\resources\messagebased.py", line 519, in read
    message = self._read_raw().decode(enco)
              ^^^^^^^^^^^^^^^^
  File "D:\PyProject\.venv\Lib\site-packages\pyvisa\resources\messagebased.py", line 473, in _read_raw
    chunk, status = self.visalib.read(self.session, size)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyProject\.venv\Lib\site-packages\pyvisa\ctwrapper\functions.py", line 2339, in read
    ret = library.viRead(session, buffer, count, byref(return_count))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyProject\.venv\Lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 227, in _return_handler
    return self.handle_return_value(session, ret_value)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyProject\.venv\Lib\site-packages\pyvisa\highlevel.py", line 252, in handle_return_value
    raise errors.VisaIOError(rv)
pyvisa.errors.VisaIOError: VI_ERROR_IO (-1073807298): Could not perform operation because of I/O error.

2025-04-11 09:34:01 - ½Å±¾Ö´ÐÐÊ§°Ü£¬·µ»ØÂë: 1
2025-04-11 09:34:01 - ´íÎóÊä³ö: Traceback (most recent call last):
  File "D:\PyProject\QTneedle\QTneedle\Standard I-V test program use Keithley2450.py", line 64, in <module>
    keithley.wires
  File "D:\PyProject\.venv\Lib\site-packages\pymeasure\instruments\common_base.py", line 298, in __getattribute__
    return super().__getattribute__(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyProject\.venv\Lib\site-packages\pymeasure\instruments\common_base.py", line 555, in fget
    vals = self.values(command_process(get_command),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyProject\.venv\Lib\site-packages\pymeasure\instruments\common_base.py", line 406, in values
    results = self.ask(command, **kwargs).strip()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyProject\.venv\Lib\site-packages\pymeasure\instruments\common_base.py", line 387, in ask
    return self.read()
           ^^^^^^^^^^^
  File "D:\PyProject\.venv\Lib\site-packages\pymeasure\instruments\instrument.py", line 173, in read
    return self.adapter.read(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyProject\.venv\Lib\site-packages\pymeasure\adapters\adapter.py", line 108, in read
    read = self._read(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\PyProject\.venv\Lib\site-packages\pymeasure\adapters\visa.py", line 172, in _read
    return self.connection.read(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyProject\.venv\Lib\site-packages\pyvisa\resources\messagebased.py", line 519, in read
    message = self._read_raw().decode(enco)
              ^^^^^^^^^^^^^^^^
  File "D:\PyProject\.venv\Lib\site-packages\pyvisa\resources\messagebased.py", line 473, in _read_raw
    chunk, status = self.visalib.read(self.session, size)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyProject\.venv\Lib\site-packages\pyvisa\ctwrapper\functions.py", line 2339, in read
    ret = library.viRead(session, buffer, count, byref(return_count))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyProject\.venv\Lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 227, in _return_handler
    return self.handle_return_value(session, ret_value)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyProject\.venv\Lib\site-packages\pyvisa\highlevel.py", line 252, in handle_return_value
    raise errors.VisaIOError(rv)
pyvisa.errors.VisaIOError: VI_ERROR_IO (-1073807298): Could not perform operation because of I/O error.

2025-04-11 09:34:37 - ½Å±¾Ö´ÐÐÊ§°Ü£¬·µ»ØÂë: 1
2025-04-11 09:34:37 - ´íÎóÊä³ö: Traceback (most recent call last):
  File "D:\Pycharm\PyCharm 2024.3.3\plugins\python-ce\helpers\pydev\pydevd.py", line 1570, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Pycharm\PyCharm 2024.3.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:\PyProject\QTneedle\QTneedle\Standard I-V test program use Keithley2450.py", line 64, in <module>
    keithley.wires
  File "D:\PyProject\.venv\Lib\site-packages\pymeasure\instruments\common_base.py", line 298, in __getattribute__
    return super().__getattribute__(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyProject\.venv\Lib\site-packages\pymeasure\instruments\common_base.py", line 555, in fget
    vals = self.values(command_process(get_command),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyProject\.venv\Lib\site-packages\pymeasure\instruments\common_base.py", line 406, in values
    results = self.ask(command, **kwargs).strip()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyProject\.venv\Lib\site-packages\pymeasure\instruments\common_base.py", line 387, in ask
    return self.read()
           ^^^^^^^^^^^
  File "D:\PyProject\.venv\Lib\site-packages\pymeasure\instruments\instrument.py", line 173, in read
    return self.adapter.read(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyProject\.venv\Lib\site-packages\pymeasure\adapters\adapter.py", line 108, in read
    read = self._read(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\PyProject\.venv\Lib\site-packages\pymeasure\adapters\visa.py", line 172, in _read
    return self.connection.read(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyProject\.venv\Lib\site-packages\pyvisa\resources\messagebased.py", line 519, in read
    message = self._read_raw().decode(enco)
              ^^^^^^^^^^^^^^^^
  File "D:\PyProject\.venv\Lib\site-packages\pyvisa\resources\messagebased.py", line 473, in _read_raw
    chunk, status = self.visalib.read(self.session, size)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyProject\.venv\Lib\site-packages\pyvisa\ctwrapper\functions.py", line 2339, in read
    ret = library.viRead(session, buffer, count, byref(return_count))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyProject\.venv\Lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 227, in _return_handler
    return self.handle_return_value(session, ret_value)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyProject\.venv\Lib\site-packages\pyvisa\highlevel.py", line 252, in handle_return_value
    raise errors.VisaIOError(rv)
pyvisa.errors.VisaIOError: VI_ERROR_IO (-1073807298): Could not perform operation because of I/O error.

2025-04-11 09:50:35 - ³É¹¦Ö´ÐÐIU²ÎÊý¼ÆËã
2025-04-11 09:54:09 - ³É¹¦Ö´ÐÐIU²ÎÊý¼ÆËã
2025-04-11 09:54:47 - Ì½ÕëÍùÏÂÒÆ¶¯ÁË
2025-04-11 09:54:54 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 09:54:59 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 09:55:01 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 09:55:04 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 09:55:05 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 09:55:06 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 09:55:07 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 09:55:09 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 09:55:10 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 09:55:11 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 09:55:13 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 09:55:15 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 09:55:16 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 09:55:17 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 09:55:18 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 09:55:19 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 09:55:20 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 09:55:22 - Ì½ÕëÍùÉÏÒÆ¶¯ÁË
2025-04-11 09:55:26 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 09:57:38 - Ì½ÕëÍùÏÂÒÆ¶¯ÁË
2025-04-11 09:57:50 - Ì½ÕëÍùÏÂÒÆ¶¯ÁË
2025-04-11 09:57:58 - Ì½ÕëÍù×óÒÆ¶¯ÁË
2025-04-11 09:59:11 - Ì½ÕëÍùÏÂÒÆ¶¯ÁË
2025-04-11 10:00:27 - Ì½ÕëÍùÉÏÒÆ¶¯ÁË
2025-04-11 10:00:44 - Ì½ÕëÍùÏÂÒÆ¶¯ÁË
2025-04-11 10:01:48 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 10:01:51 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 10:01:52 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 10:01:53 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 10:01:54 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 10:01:56 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 10:01:57 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 10:01:58 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 10:02:00 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 10:02:02 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 10:02:03 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 10:02:05 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 10:02:08 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 10:02:10 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 10:02:12 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 10:02:17 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 10:02:19 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 10:02:21 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 10:02:23 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 10:02:25 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 10:02:27 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 10:02:28 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 10:02:30 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 10:02:32 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 10:02:34 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 10:02:42 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:02:44 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:02:47 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:04:51 - Ì½ÕëÍùÉÏÒÆ¶¯ÁË
2025-04-11 10:05:28 - Ì½ÕëÍùÉÏÒÆ¶¯ÁË
2025-04-11 10:09:08 - Ì½ÕëÏÂÑ¹ÁË 10
2025-04-11 10:09:10 - Ì½ÕëÏÂÑ¹ÁË 10
2025-04-11 10:09:11 - Ì½ÕëÏÂÑ¹ÁË 10
2025-04-11 10:09:12 - Ì½ÕëÏÂÑ¹ÁË 10
2025-04-11 10:09:13 - Ì½ÕëÏÂÑ¹ÁË 10
2025-04-11 10:09:21 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:09:23 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:09:24 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:09:25 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:09:26 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:09:27 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:09:28 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:09:29 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:09:35 - Ì½ÕëÍùÓÒÒÆ¶¯ÁË
2025-04-11 10:09:46 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:09:46 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:09:47 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:09:48 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:09:50 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:09:51 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:09:52 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:09:53 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:09:54 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:09:55 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:09:57 - Ì½ÕëÍù×óÒÆ¶¯ÁË
2025-04-11 10:10:03 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:10:05 - Ì½ÕëÍù×óÒÆ¶¯ÁË
2025-04-11 10:10:24 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:10:25 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:10:27 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:10:28 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:10:46 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:10:48 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:10:49 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:10:50 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:10:51 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:10:59 - Ì½ÕëÍùÏÂÒÆ¶¯ÁË
2025-04-11 10:15:38 - Ì½ÕëÍùÉÏÒÆ¶¯ÁË
2025-04-11 10:15:45 - Ì½ÕëÍùÉÏÒÆ¶¯ÁË
2025-04-11 10:16:01 - Ì½ÕëÏÂÑ¹ÁË 100
2025-04-11 10:16:03 - Ì½ÕëÏÂÑ¹ÁË 100
2025-04-11 10:16:04 - Ì½ÕëÏÂÑ¹ÁË 100
2025-04-11 10:16:05 - Ì½ÕëÏÂÑ¹ÁË 100
2025-04-11 10:16:06 - Ì½ÕëÏÂÑ¹ÁË 100
2025-04-11 10:16:07 - Ì½ÕëÏÂÑ¹ÁË 100
2025-04-11 10:16:08 - Ì½ÕëÏÂÑ¹ÁË 100
2025-04-11 10:16:08 - Ì½ÕëÏÂÑ¹ÁË 100
2025-04-11 10:20:54 - Ì½ÕëÍùÉÏÒÆ¶¯ÁË
2025-04-11 10:20:58 - Ì½ÕëÍùÓÒÒÆ¶¯ÁË
2025-04-11 10:21:01 - Ì½ÕëÍùÏÂÒÆ¶¯ÁË
2025-04-11 10:21:04 - Ì½ÕëÍùÓÒÒÆ¶¯ÁË
2025-04-11 10:21:26 - Ì½ÕëÏÂÑ¹ÁË 10
2025-04-11 10:21:28 - Ì½ÕëÏÂÑ¹ÁË 10
2025-04-11 10:21:29 - Ì½ÕëÏÂÑ¹ÁË 10
2025-04-11 10:21:31 - Ì½ÕëÏÂÑ¹ÁË 10
2025-04-11 10:21:32 - Ì½ÕëÏÂÑ¹ÁË 10
2025-04-11 10:21:36 - Ì½ÕëÏÂÑ¹ÁË 100
2025-04-11 10:21:37 - Ì½ÕëÏÂÑ¹ÁË 100
2025-04-11 10:21:39 - Ì½ÕëÏÂÑ¹ÁË 100
2025-04-11 10:21:44 - Ì½ÕëÏÂÑ¹ÁË 100
2025-04-11 10:21:46 - Ì½ÕëÏÂÑ¹ÁË 100
2025-04-11 10:21:47 - Ì½ÕëÏÂÑ¹ÁË 100
2025-04-11 10:23:12 - Ì½ÕëÏÂÑ¹ÁË 100
2025-04-11 10:23:16 - Ì½ÕëÏÂÑ¹ÁË 100
2025-04-11 10:23:19 - Ì½ÕëÏÂÑ¹ÁË 100
2025-04-11 10:23:26 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:23:27 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:23:28 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:23:29 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:23:30 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:23:31 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:23:32 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:23:33 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:23:34 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:23:35 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:23:36 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:23:37 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:23:38 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:23:38 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:23:39 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:23:40 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:23:41 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:23:42 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:23:43 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:23:44 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:23:45 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:23:55 - Ì½ÕëÍùÏÂÒÆ¶¯ÁË
2025-04-11 10:23:58 - Ì½ÕëÍùÏÂÒÆ¶¯ÁË
2025-04-11 10:24:39 - Ì½ÕëÍùÉÏÒÆ¶¯ÁË
2025-04-11 10:25:42 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:25:43 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:25:44 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:26:33 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:26:34 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:26:35 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:26:36 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:26:37 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:26:37 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:26:38 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:26:39 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:26:40 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:26:41 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:26:42 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:26:43 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:26:44 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:26:44 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:26:45 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:26:46 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:26:47 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:26:48 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:26:49 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:26:50 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:26:57 - Ì½ÕëÍùÏÂÒÆ¶¯ÁË
2025-04-11 10:27:09 - Ì½ÕëÏÂÑ¹ÁË 100
2025-04-11 10:27:11 - Ì½ÕëÏÂÑ¹ÁË 100
2025-04-11 10:27:12 - Ì½ÕëÏÂÑ¹ÁË 100
2025-04-11 10:27:13 - Ì½ÕëÏÂÑ¹ÁË 100
2025-04-11 10:27:14 - Ì½ÕëÏÂÑ¹ÁË 100
2025-04-11 10:27:15 - Ì½ÕëÏÂÑ¹ÁË 100
2025-04-11 10:27:16 - Ì½ÕëÏÂÑ¹ÁË 100
2025-04-11 10:27:17 - Ì½ÕëÏÂÑ¹ÁË 100
2025-04-11 10:27:18 - Ì½ÕëÏÂÑ¹ÁË 100
2025-04-11 10:27:41 - Ì½ÕëÍùÉÏÒÆ¶¯ÁË
2025-04-11 10:28:55 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:28:56 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:28:57 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:28:58 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:28:59 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:29:00 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:29:01 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:29:01 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:29:02 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:29:03 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:29:04 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:29:05 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:29:06 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:29:07 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:29:08 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:29:09 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:29:09 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:29:10 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:29:11 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:29:12 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 10:44:17 - ½Å±¾Êä³ö: ---

2025-04-11 10:44:17 - ³É¹¦Ö´ÐÐIU²ÎÊý¼ÆËã
2025-04-11 10:59:08 - Ì½ÕëÍùÉÏÒÆ¶¯ÁË
2025-04-11 10:59:20 - Ì½ÕëÏÂÑ¹ÁË 10
2025-04-11 11:00:06 - Ì½ÕëÍùÏÂÒÆ¶¯ÁË
2025-04-11 11:00:51 - Ì½ÕëÌ§ÉýÁË 30.0
2025-04-11 11:00:53 - Ì½ÕëÏÂÑ¹ÁË 30.0
2025-04-11 11:00:55 - Ì½ÕëÏÂÑ¹ÁË 30.0
2025-04-11 11:01:12 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:01:14 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:01:15 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:01:16 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:01:18 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:01:20 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:01:22 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:01:24 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:01:26 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:01:27 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:01:29 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:01:30 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:01:31 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:01:32 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:01:34 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:01:35 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:01:36 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:01:58 - Ì½ÕëÍùÉÏÒÆ¶¯ÁË
2025-04-11 11:02:02 - Ì½ÕëÍùÏÂÒÆ¶¯ÁË
2025-04-11 11:02:06 - Ì½ÕëÍùÏÂÒÆ¶¯ÁË
2025-04-11 11:02:08 - Ì½ÕëÍùÏÂÒÆ¶¯ÁË
2025-04-11 11:03:08 - Ì½ÕëÍùÏÂÒÆ¶¯ÁË
2025-04-11 11:03:18 - Ì½ÕëÍùÉÏÒÆ¶¯ÁË
2025-04-11 11:03:21 - Ì½ÕëÍùÏÂÒÆ¶¯ÁË
2025-04-11 11:03:23 - Ì½ÕëÍùÏÂÒÆ¶¯ÁË
2025-04-11 11:03:25 - Ì½ÕëÍùÏÂÒÆ¶¯ÁË
2025-04-11 11:03:28 - Ì½ÕëÍùÏÂÒÆ¶¯ÁË
2025-04-11 11:03:30 - Ì½ÕëÍùÓÒÒÆ¶¯ÁË
2025-04-11 11:04:39 - Ì½ÕëÍù×óÒÆ¶¯ÁË
2025-04-11 11:04:59 - Ì½ÕëÍùÉÏÒÆ¶¯ÁË
2025-04-11 11:05:02 - Ì½ÕëÍùÏÂÒÆ¶¯ÁË
2025-04-11 11:05:06 - Ì½ÕëÍùÏÂÒÆ¶¯ÁË
2025-04-11 11:05:09 - Ì½ÕëÍùÉÏÒÆ¶¯ÁË
2025-04-11 11:05:13 - Ì½ÕëÍùÏÂÒÆ¶¯ÁË
2025-04-11 11:05:16 - Ì½ÕëÍùÏÂÒÆ¶¯ÁË
2025-04-11 11:05:18 - Ì½ÕëÍùÏÂÒÆ¶¯ÁË
2025-04-11 11:05:21 - Ì½ÕëÍùÏÂÒÆ¶¯ÁË
2025-04-11 11:06:26 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:06:27 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:06:28 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:06:29 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:06:30 - Ì½ÕëÍùÉÏÒÆ¶¯ÁË
2025-04-11 11:06:36 - Ì½ÕëÍùÉÏÒÆ¶¯ÁË
2025-04-11 11:06:43 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:06:44 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:06:45 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:06:46 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:06:48 - Ì½ÕëÍùÉÏÒÆ¶¯ÁË
2025-04-11 11:06:54 - Ì½ÕëÍù×óÒÆ¶¯ÁË
2025-04-11 11:06:59 - Ì½ÕëÍùÉÏÒÆ¶¯ÁË
2025-04-11 11:07:03 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:07:04 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:07:05 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:07:06 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:07:07 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:07:08 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:07:09 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:07:09 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:07:10 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:07:11 - Ì½ÕëÍùÉÏÒÆ¶¯ÁË
2025-04-11 11:07:15 - Ì½ÕëÍùÏÂÒÆ¶¯ÁË
2025-04-11 11:07:20 - Ì½ÕëÍùÉÏÒÆ¶¯ÁË
2025-04-11 11:07:28 - Ì½ÕëÍùÓÒÒÆ¶¯ÁË
2025-04-11 11:07:33 - Ì½ÕëÍùÏÂÒÆ¶¯ÁË
2025-04-11 11:09:06 - Ì½ÕëÍùÓÒÒÆ¶¯ÁË
2025-04-11 11:09:10 - Ì½ÕëÍùÓÒÒÆ¶¯ÁË
2025-04-11 11:09:14 - Ì½ÕëÍùÉÏÒÆ¶¯ÁË
2025-04-11 11:09:17 - Ì½ÕëÍùÉÏÒÆ¶¯ÁË
2025-04-11 11:09:20 - Ì½ÕëÍùÓÒÒÆ¶¯ÁË
2025-04-11 11:09:26 - Ì½ÕëÍù×óÒÆ¶¯ÁË
2025-04-11 11:09:31 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:09:32 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:09:33 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:09:34 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:09:35 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:09:36 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:09:37 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:09:38 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:09:39 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:09:46 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:09:47 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:09:48 - Ì½ÕëÌ§ÉýÁË 100
2025-04-11 11:09:49 - Ì½ÕëÍùÓÒÒÆ¶¯ÁË
2025-04-11 11:10:07 - Ì½ÕëÍùÉÏÒÆ¶¯ÁË
2025-04-11 11:16:45 - Ì½ÕëÍù×óÒÆ¶¯ÁË
2025-04-11 11:17:21 - Ì½ÕëÍùÏÂÒÆ¶¯ÁË
2025-04-11 11:17:51 - Ì½ÕëÍùÉÏÒÆ¶¯ÁË
2025-04-11 11:18:02 - Ì½ÕëÍùÓÒÒÆ¶¯ÁË
2025-04-11 11:18:26 - Ì½ÕëÍùÏÂÒÆ¶¯ÁË
2025-04-11 11:18:39 - Ì½ÕëÍùÉÏÒÆ¶¯ÁË
2025-04-11 11:19:03 - Ì½ÕëÍùÏÂÒÆ¶¯ÁË 279.508
2025-04-11 11:19:04 - Ì½ÕëÍù×óÒÆ¶¯ÁË 279.508
2025-04-11 11:19:05 - Ì½ÕëÍùÏÂÒÆ¶¯ÁË 235.85
2025-04-11 11:19:06 - Ì½ÕëÍùÓÒÒÆ¶¯ÁË 235.85
2025-04-11 11:19:19 - Ì½ÕëÍùÉÏÒÆ¶¯ÁË
2025-04-11 11:19:32 - Ì½ÕëÍùÉÏÒÆ¶¯ÁË
2025-04-11 11:19:35 - Ì½ÕëÍùÏÂÒÆ¶¯ÁË
2025-04-11 11:19:38 - Ì½ÕëÍùÉÏÒÆ¶¯ÁË
2025-04-11 11:20:03 - Ì½ÕëÍùÏÂÒÆ¶¯ÁË 127.475
2025-04-11 11:20:03 - Ì½ÕëÍùÓÒÒÆ¶¯ÁË 127.475
2025-04-11 11:22:18 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 11:22:19 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 11:22:20 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 11:22:21 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 11:22:22 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 11:22:22 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 11:22:23 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 11:22:24 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 11:22:25 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 11:22:26 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 11:22:27 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 11:22:28 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 11:22:28 - Ì½ÕëÌ§ÉýÁË 10
2025-04-11 11:25:01 - Ì½ÕëÍù×óÒÆ¶¯ÁË
2025-04-11 11:25:27 - Ì½ÕëÍùÓÒÒÆ¶¯ÁË
2025-04-11 11:25:52 - Ì½ÕëÍùÏÂÒÆ¶¯ÁË
2025-04-11 11:26:05 - Ì½ÕëÍùÉÏÒÆ¶¯ÁË
2025-04-11 11:26:22 - Ì½ÕëÍùÏÂÒÆ¶¯ÁË 125.0
2025-04-11 11:26:23 - Ì½ÕëÍù×óÒÆ¶¯ÁË 125.0
2025-04-11 11:29:33 - Ì½ÕëÍùÏÂÒÆ¶¯ÁË 160.078
2025-04-11 11:29:34 - Ì½ÕëÍù×óÒÆ¶¯ÁË 160.078
